image: Ubuntu  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

ktor:
  development: true
  deployment:
    watch:
      - classes

install:
  # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-mbank.jar &


build_script:
  - chmod +x gradlew
  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации